# This is a basic workflow to help you get started with Actions

name: Euler CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: install guile
        run: sudo apt install guile-3.0
      - name: dev guile
        run: sudo apt-get install guile-3.0-dev
      - name: Check-exists guile
        run: echo "(display \"Hello\")" > tmp.scm | guile tmp.scm
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
      - name: Check-exists Python
        run: echo "print(1)" > tmp.scm | python3 tmp.scm
      - name: clean
        run: rm tmp.scm
      - name: install PyLint
        run: pip install pylint
        
      # Runs a single command using the runners shell
      - name: Run PyLint
        run: find src/ -type f -name "*.py" | xargs pylint 

      - name: Use gcc
        run: cd src && make

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: See files
        run: ls -l
        
      - name: 12. Py
        run: cd Lab1/src && python3 task_12.py
      - name: 12. Endless list
        run: cd Lab1/src && guile 12_endlist.scm
      - name: 12. Recursion
        run: cd Lab1/src && guile 12_rec.scm
      - name: 12. Guile + C
        run: cd Lab1/src && ./12_withc
      - name: 19. Py
        run: cd Lab1/src && python3 task_19.py
      - name: 19. Tailrec
        run: cd Lab1/src && guile 19_tailrec.scm
      - name: 19. Map + Fold
        run: cd Lab1/src && guile 19_mapfold.scm
      - name: 19. Guile + C
        run: cd Lab1/src && ./19_withc
  
