# This is a basic workflow to help you get started with Actions

name: RB-Bag CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt install guile-3.0
          sudo apt-get install guile-3.0-dev
          echo "(display \"Hello\")" > tmp.scm | guile tmp.scm
          rm tmp.scm
        
      - name: Setup project
        run: cd Lab2 && make format

      - name: RB-Tree Unit tests
        run: cd Lab2 && make rb-tree-unit

      - name: RB-Bag Unit tests
        run: cd Lab2 && make rb-bag-unit

      - name: RB-Bag Property tests
        run: cd Lab2 && make rb-bag-property

          
  
